server:
  port: 8081

spring:
  dubbo:
    application:
      name: springboot-dubbo-demo
    registry:
      address: zookeeper://dev.cdh.ecarx.local:2181 #zookeeper地址
      port: 2181
    scan: com.zjut.dubbo.consumer.call.impl